name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    steps:
      - name: Publish
        run: echo "Publish"